spring.application.name=owners-gate

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.encoding=UTF-8
spring.jpa.show-sql=true
# spring.h2.console.enabled=true


# ※実務本番では環境変数で上書きするが学習用は以下の記述を採用する

# H2Databaseの設定（開発用）
# spring.datasource.url=jdbc:h2:file:./data/owners_gate_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# テーブルはHibernateに自動生成させず、schema.sql / data.sql で管理する
# 起動時に必ず schema.sql -> data.sql を実行する（ファイルDBでも実行させる設定）
# spring.sql.init.mode=always

# PostgreSQLの設定（GitHub/AWSデプロイ用）
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres9999
spring.datasource.driver-class-name=org.postgresql.Driver
# PostgreSQL時はspring.sql.init.mode は書かない（デフォルトのembeddedのまま）

